export const queryKeys = {
  demoProfiles: ['demo-profiles'] as const,
  authSessionRoot: ['auth-session'] as const,
  authSession: (profileId: string, restoreNonce: number) => ['auth-session', profileId, restoreNonce] as const,
  tools: ['tools'] as const,
  catalog: ['tool-catalog'] as const,
  activity: ['worker-activity'] as const,
  adminSummary: ['admin-summary'] as const,
  adminSummaryFor: (actorId: string) => ['admin-summary', actorId] as const,
  adminPeopleRoot: ['admin-people'] as const,
  adminPeople: (actorId: string) => ['admin-people', actorId] as const,
  adminPersonRoot: ['admin-person'] as const,
  adminPerson: (actorId: string, personId: string) => ['admin-person', actorId, personId] as const,
  adminPermissions: (actorId: string) => ['admin-permissions', actorId] as const,
  adminWarehousesRoot: ['admin-warehouses'] as const,
  adminWarehouses: (actorId: string) => ['admin-warehouses', actorId] as const,
  pendingHandoffsRoot: ['pending-handoffs'] as const,
  pendingHandoffs: (profileId: string) => ['pending-handoffs', profileId] as const,
  transferTargetsRoot: ['transfer-targets'] as const,
  toolDetailRoot: ['tool-detail'] as const,
  toolDetail: (toolUnitId: string) => ['tool-detail', toolUnitId] as const,
  transferTargets: (actorId: string, toolUnitId: string, handoffId?: string) =>
    handoffId
      ? (['transfer-targets', actorId, toolUnitId, handoffId] as const)
      : (['transfer-targets', actorId, toolUnitId] as const),
  warehouseQueueRoot: ['warehouse-queue'] as const,
  warehouseScopesRoot: ['warehouse-scopes'] as const,
  warehouseScopes: (actorId: string) => ['warehouse-scopes', actorId] as const,
  warehouseQueue: (actorId: string, warehouseId: string) => ['warehouse-queue', actorId, warehouseId] as const,
  warehouseInventoryRoot: ['warehouse-inventory'] as const,
  warehouseInventory: (actorId: string, warehouseId: string, includeArchived: boolean) =>
    ['warehouse-inventory', actorId, warehouseId, includeArchived] as const,
  warehouseOperationsRoot: ['warehouse-operations'] as const,
  warehouseOperationsSummary: (actorId: string, warehouseId: string) =>
    ['warehouse-operations', actorId, warehouseId, 'summary'] as const,
  adminAuditRoot: ['admin-audit'] as const,
  adminAudit: (actorId: string) => ['admin-audit', actorId] as const,
  companyProfile: ['company-profile'] as const,
  toolCategories: ['tool-categories'] as const,
};
